RestaurantReview/Controllers/RestaurantReviewsController.cs
using RestaurantReview.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantReview.Controllers
{
    public class RestaurantReviewsController : Controller
    {
        private RestaurantContext context = new RestaurantContext();
        //
        // GET: /RestaurantReviews/

        public ActionResult Index([Bind(Prefix= "id")] int restaurentId)
        {
            var restaurent = context.Restaurants.Find(restaurentId);
            restaurent.Reviews = context.Reviews.Where(p => p.RestaurantId == restaurentId).ToList();
            if(restaurent != null)
            {
                return View(restaurent);
            }
            return HttpNotFound();
        }

        //
        // GET: /RestaurantReviews/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /RestaurantReviews/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /RestaurantReviews/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /RestaurantReviews/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /RestaurantReviews/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /RestaurantReviews/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /RestaurantReviews/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RestaurantReview/Views/Restaurants_Old/Index.cshtml
@*@model RestaurantReview.Models.RestaurantViewModel*@

@*@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach (var item in Model){
    <div>
        <h4>@item.Name</h4>
        <div>@item.City, @item.Country</div>
        <div>Reviews : @item.CountOfReviews</div>
    </div>
}*@



@model IEnumerable<RestaurantReview.Models.RestaurantViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th></th>
        <th>Name</th>
        <th>City</th>
        <th>Country</th>
        <th></th>
        <th>Count Reviews</th>

       @* <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CountOfReviews)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CountOfReviews)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Reviews", "Index", "RestaurantReviews", new { id=item.Id}, null)
        </td>
        <td>@item.Name</td>
        <td>@item.City</td>
        <td>@item.Country</td>
        <td>@item.CountOfReviews</td>
    </tr>
}

</table>